# cluster.yaml
# An example of ClusterConfig containing Windows and Linux node groups to support Windows workloads
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: Test-windows-cluster
  region: us-east-1

nodeGroups:
  - name: windows-ng
    amiFamily: WindowsServer2019FullContainer
    minSize: 1
    maxSize: 2

managedNodeGroups:
  - name: linux-ng
    instanceType: t2.large
    minSize: 1
    maxSize: 2
