---
apiVersion: v1
kind: Service
metadata:
  name: winiis
  labels:
    run: winiis
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: winiis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: winiis
  name: winiis
  namespace: default
spec:
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: winiis
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: winiis
    spec:
      nodeSelector:
        beta.kubernetes.io/os: windows
      # Windows Build only supported on EKS 1.17+. If lower version remove the selector
        node.kubernetes.io/windows-build: '10.0.17763'
      containers:
        - image: public.ecr.aws/t4b4b8z3/bgsilvait/iis:latest
          imagePullPolicy: IfNotPresent
          name: winiis
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_SERVICE_ACCOUNT
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
      tolerations:
      - effect: NoSchedule
        key: os
        operator: Equal
        value: Win1809
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
